- README.md
favor de revisar mi trabajo y en caso de ser apropiado favor de aprobar el merge
> prueba rama nueva

- src/main/java/io/kebblar/petstore/api/mapper/DireccionMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/Direccion.java
- src/main/java/io/kebblar/petstore/api/model/domain/Pais.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/HttpStatus.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/MapperCallException.java
- src/main/java/io/kebblar/petstore/api/rest/AccessController.java
- src/main/java/io/kebblar/petstore/api/service/ContadorServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/DireccionService.java
- src/main/resources/application.properties
By goose
pero en realidad lo debe de crear Faby y que lo revisen sus compañeros de equipo
> Enviando solo los archivos de mi pull request

- src/main/java/io/kebblar/petstore/api/mapper/UsuarioDetalleMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/Estado.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/ControllerException.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/WrongTokenException.java
- src/main/java/io/kebblar/petstore/api/model/response/ProcesaMascotaResponse.java
- src/main/java/io/kebblar/petstore/api/rest/MascotaController.java
- src/main/java/io/kebblar/petstore/api/service/MascotaServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioService.java
> Enviando solo los archivos del pull request

- src/main/java/io/kebblar/petstore/api/mapper/ContadorMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/UsuarioDetalle.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/BadCredentialsException.java
- src/main/java/io/kebblar/petstore/api/model/exceptions/MailException.java
- src/main/java/io/kebblar/petstore/api/model/request/CredencialesRequest.java
- src/main/java/io/kebblar/petstore/api/rest/PruebaController.java
- src/main/java/io/kebblar/petstore/api/service/PaisService.java
- src/main/java/io/kebblar/petstore/api/service/TipoDireccionServiceImpl.java
> Se suben solamente los cambios de la clase.

- src/test/java/io/kebblar/petstore/api/service/TestCriptomonedas.java
Arreglandod etalles del test de criptos
> Solucionando problemas con el test de Criptomonedas

- src/main/java/io/kebblar/petstore/api/mapper/EstatusAnuncioMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/EstatusAnuncio.java
- src/main/java/io/kebblar/petstore/api/rest/EstatusAnuncioController.java
- src/main/java/io/kebblar/petstore/api/service/EstatusAnuncioService.java
- src/main/java/io/kebblar/petstore/api/service/EstatusAnuncioServiceImpl.java
Se crea el crud para la administracion del catalogo de anuncio
> Se crea el crud para la administracion del Catalogo Anuncio

- src/main/java/io/kebblar/petstore/api/mapper/AtributoMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/CategoriaAtributoMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/CategoriaMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/ValorAtributoMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/Atributo.java
- src/main/java/io/kebblar/petstore/api/model/domain/AtributoDetalleTO.java
- src/main/java/io/kebblar/petstore/api/model/domain/AtributoTO.java
- src/main/java/io/kebblar/petstore/api/model/domain/Categoria.java
- src/main/java/io/kebblar/petstore/api/model/domain/CategoriaAtributo.java
- src/main/java/io/kebblar/petstore/api/model/domain/CategoriaDetallesTO.java
- src/main/java/io/kebblar/petstore/api/model/domain/CategoriaTO.java
- src/main/java/io/kebblar/petstore/api/model/domain/ValorAtributo.java
- src/main/java/io/kebblar/petstore/api/rest/AtributoController.java
- src/main/java/io/kebblar/petstore/api/rest/CategoriaAtributoController.java
- src/main/java/io/kebblar/petstore/api/rest/CategoriaController.java
- src/main/java/io/kebblar/petstore/api/rest/ValorAtributoController.java
- src/main/java/io/kebblar/petstore/api/service/AtributoService.java
- src/main/java/io/kebblar/petstore/api/service/AtributoServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/CategoriaAtributoService.java
- src/main/java/io/kebblar/petstore/api/service/CategoriaAtributoServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/CategoriaService.java
- src/main/java/io/kebblar/petstore/api/service/CategoriaServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/ValorAtributoService.java
- src/main/java/io/kebblar/petstore/api/service/ValorAtributoServiceImpl.java
Categoria
Atributo
Categoria_atributo
Valor_atributo
El motivo de que este commit este muy grande es dedido a que se tiene
mucha dependencia entre ellos
> Sec crean los crud de  categoria atributo rango:

- src/main/java/io/kebblar/petstore/api/mapper/MediaTipoMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/MediaTipo.java
- src/main/java/io/kebblar/petstore/api/rest/MediaTipoController.java
- src/main/java/io/kebblar/petstore/api/service/MediaTipoService.java
- src/main/java/io/kebblar/petstore/api/service/MediaTipoServiceImpl.java
Se anexan los archivos necesarios para el crud del catalogo media tipo
> Se anexan los archivos necesarios para el crud del catalogo media tipo

- src/main/java/io/kebblar/petstore/api/mapper/GraficaCompradorMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/GraficaMascotaMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/GraficaPaqueteriaMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/GraficaComprador.java
- src/main/java/io/kebblar/petstore/api/model/domain/GraficaMascota.java
- src/main/java/io/kebblar/petstore/api/model/domain/GraficaPaqueteria.java
- src/main/java/io/kebblar/petstore/api/rest/GraficaController.java
- src/main/java/io/kebblar/petstore/api/service/GraficaService.java
- src/main/java/io/kebblar/petstore/api/service/GraficaServiceImpl.java
mas asiduo, Paqueteria mas utilizada, MAscota mas vendida)
> Se agregan servicios para alimentar las siguiente graficas (Comprador

- src/main/java/io/kebblar/petstore/api/mapper/EstadoMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/MunicipioMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/PaisMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/Estado.java
- src/main/java/io/kebblar/petstore/api/model/domain/Municipio.java
- src/main/java/io/kebblar/petstore/api/rest/EstadoController.java
- src/main/java/io/kebblar/petstore/api/rest/MunicipioController.java
- src/main/java/io/kebblar/petstore/api/rest/PaisController.java
- src/main/java/io/kebblar/petstore/api/service/EstadoService.java
- src/main/java/io/kebblar/petstore/api/service/EstadoServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioService.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/PaisService.java
- src/main/java/io/kebblar/petstore/api/service/PaisServiceImpl.java
Se crea una nueva rama para asi no tener tantos conflictos con el pull request anterior
> Crud de los catalogos de municipio estado pais

- src/main/java/io/kebblar/petstore/api/utils/Convert.java
- src/main/java/io/kebblar/petstore/api/utils/CreatePDF.java
Se agrego java doc a metodos en clases, CreatePDF y Convert
> Se corrigen comentarios por PR, agregando java doc a clases

- src/main/java/io/kebblar/petstore/api/model/request/BusquedaAdministracionRequest.java
- src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
Se solicita integración de mejoras a la gestión de anuncios.
> Se modifica el folio de la busqueda por un string

- src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
- src/main/resources/application-dev.properties
**Se corrige el problema de las imágenes**
> Se corrige el path para que se puedan ver las imagenes

- src/main/java/io/kebblar/petstore/api/mapper/GraficaTotalFechasCategoriaMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/GraficaTotalFechasCategoria.java
- src/main/java/io/kebblar/petstore/api/rest/GraficaTotalFechasCategoriaController.java
- src/main/java/io/kebblar/petstore/api/service/GraficaTotalFechasCategoriaService.java
- src/main/java/io/kebblar/petstore/api/service/GraficaTotalFechasCategoriaServiceImpl.java
Se crean modelo, mapper, service y rest para la creación de JSON con datos para la gráfica montos por categoría
> Grafica Montos por Categoria

- src/main/java/io/kebblar/petstore/api/model/response/BusquedaAdministracionResponse.java
Se solicita el siguiente pull request para corregir bug de búsqueda administrativa de anuncios
> Se corrige bug de busqueda administrativa de anuncios

- src/main/java/io/kebblar/petstore/api/service/CategoriaServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/PaisServiceImpl.java
Se agrega mensaje de Exception para los Servicios de Pais y Categoria
> Se agrega mensaje de Exception para los Servicios de Pais y Categoria

- src/main/java/io/kebblar/petstore/api/utils/Convert.java
- src/main/java/io/kebblar/petstore/api/utils/CreatePDF.java
Se realizo la adecuación para mostrar la descripción del articulo y no aparezca con formato HTML
> Se modifica la descripción del articulo ya que aparecia con formato html

- src/main/java/io/kebblar/petstore/api/mapper/EstadoMapper.java
- src/main/java/io/kebblar/petstore/api/mapper/MunicipioMapper.java
- src/main/java/io/kebblar/petstore/api/rest/EstadoController.java
- src/main/java/io/kebblar/petstore/api/rest/MunicipioController.java
- src/main/java/io/kebblar/petstore/api/service/EstadoService.java
- src/main/java/io/kebblar/petstore/api/service/EstadoServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioService.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioServiceImpl.java
Se crea pull request para los filtros de los estados, pais y municipio
> Se agregan los servicios para los filtros

- src/main/java/io/kebblar/petstore/api/mapper/GraficaVentasTotalesMapper.java
- src/main/java/io/kebblar/petstore/api/model/domain/GraficaVentasTotales.java
- src/main/java/io/kebblar/petstore/api/rest/GraficaVentasTotalesController.java
- src/main/java/io/kebblar/petstore/api/service/GraficaVentasTotalesService.java
- src/main/java/io/kebblar/petstore/api/service/GraficaVentasTotalesServiceImpl.java
Se añaden model, mapper, service, rest para gráficas de total de ventas (importe y número de órdenes de compra) y total de ventas con filtro de fecha
> Se realiza back end para gráficas de ventas totales

- src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
- src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
- src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
Se solicita el siguiente pull request que contempla los siguientes cambios
1.- Se valida que el anuncio no venga nulo en la búsqueda
2.- Se agrega zona horaria de México
3.- Se agrega ordenamiento de anuncios
4.- Se agregan pruebas unitarias
> Integración pruebas unitarias y mejoras

- src/main/java/io/kebblar/petstore/api/rest/MunicipioController.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioServiceImpl.java
- src/test/java/io/kebblar/petstore/api/service/TestCatalogos.java
> Se soluciona bug en el filtro de pais en consulta municipio. 

- pom.xml
- src/main/java/io/kebblar/petstore/api/model/domain/Anuncio.java
- src/main/java/io/kebblar/petstore/api/model/response/DetalleAnuncioResponse.java
- src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
- src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
- src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
**Se solicita el siguiente pull request para el manejo de fechas**
> Bug en el manejo de fechas

- pom.xml
- src/main/java/io/kebblar/petstore/api/model/domain/Anuncio.java
- src/main/java/io/kebblar/petstore/api/model/response/DetalleAnuncioResponse.java
- src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
- src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
- src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
Reverts kebblar/petstore-back#276
> Revert "Bug en el manejo de fechas"

- src/main/java/io/kebblar/petstore/api/mapper/GraficaMascotaMapper.java
Favor de integrar este cambio, se corrige query, para mostrar la información de manera correcta
> Se corrige consulta para mostrar grafica de mascota mas vendida top 5

- src/main/java/io/kebblar/petstore/api/service/EstadoServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/EstatusAnuncioServiceImpl.java
- src/main/java/io/kebblar/petstore/api/service/MunicipioServiceImpl.java
Se modifican los service implements para que retorne la excepcion mapper con un codigo de error
> Se modifican para que retornen una excepcion con el codido de error
